config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "articles#index"
  
  resources :articles do
    resources :comments
  end

  resources :manage_users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  def created_at
    attributes['created_at'].strftime("%m/%d/%Y %H:%M")
  end
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comments
  
  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10 }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  belongs_to :user

  validates :body, presence: true, length: { minimum: 10 }
end

app/models/role.rb
class Role < ApplicationRecord
  has_many :users

  validates :name, presence: true, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :role

  def name
    email
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :authenticate_user!, except: [:index, :show]

  def index
    @articles = Article.all
  end
  
  def show
    @comment = Comment.new
    @article = Article.find(params[:id])
  end
  
  def new
    @article = Article.new
  end
  
  def create
    @article = Article.new(article_params)
    
    if @article.save
      redirect_to @article, flash: { notice_article: "Article added" }
    else
      render :new
    end
  end
  
  def edit
    @article = Article.find(params[:id])
  end
  
  def update
    @article = Article.find(params[:id])
    
    if @article.update(article_params)
      redirect_to @article
    else
      render :edit
    end
  end
  
  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    
    redirect_to root_path
  end
  
  
  private
  def article_params
    params.require(:article).permit(:title, :body)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
  end

  def create
    comment_record = Comment.new(comment_params).tap do |comment|
      comment.article_id = article_id
      comment.user_id = current_user.id
    end

    if comment_record.save
      redirect_to article_path(article_id), flash: { notice_comment: "Comment added" }
    else
      redirect_to article_path(article_id), flash: { error_comment: comment_record.errors.full_messages }
    end
  end

  def destroy
    Comment.find(params[:id]).destroy
    redirect_to article_path(article_id)
  end

  private
    def comment_params
      params.require(:comment).permit(:body)
    end

    def article_id
        params[:article_id]
    end
end

app/controllers/manage_users_controller.rb
class ManageUsersController < ApplicationController

  def index
    @users = User.all
  end

  def update
    user = User.find(params[:id])
    user.update(role_id_params)
    redirect_to manage_users_path
  end

  def destroy
    User.find(params[:id]).destroy
    redirect_to manage_users_path
  end

  def role_id_params
    params.require(:user).permit(:role_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/_form.html.slim
- if flash[:notice_article]
    .col-sm-4.alert.alert-success= flash[:notice]
= form_with model: article do |form|
    div.mb-3.col-sm-6
        = form.label :title, class: 'form-label'
        = form.text_field :title, class: 'form-control'
    - article.errors.full_messages_for(:title).each do |message|
        div.alert.alert-danger
            = message
    div.mb-3.col-sm-6
        = form.label :body, class: 'form-label'
        = form.text_area :body, class: 'form-control', rows:'10'
    - article.errors.full_messages_for(:body).each do |message|
        .col-sm-4.alert.alert-danger
            = message
    div
        = form.submit 'Submit', class: 'btn btn-primary'

app/views/articles/edit.html.slim
= link_to 'Back to articles', :root
h1
  | Edit Article
= render "form", article: @article

app/views/articles/index.html.slim
h1
  | Articles
ul
  - @articles.each do |article|
    li
      = link_to article.title, article
= link_to "New Article", new_article_path, class: 'btn btn-primary col-md-2'

app/views/articles/new.html.slim
= link_to 'Back to articles', :root
h1 New Article :
= render "form", article: @article

app/views/articles/show.html.slim
= link_to 'Back to articles', :root
h1
  = @article.title
p
  = @article.body

- if current_user && current_user.role_id == 3
    .mb-4
        = link_to "Edit", edit_article_path(@article), class: 'btn btn-primary col-2 me-2'
        = link_to "Destroy", article_path(@article), method: :delete, data: { confirm: "Are you sure?" }, class: 'btn btn-danger col-2'

h2 Comments
= render @article.comments

h2 Add a comment:
- if user_signed_in?
    = render 'comments/form'
- else
    span
        = link_to('Please login to leave a comment', new_user_session_path)

app/views/comments/_comment.html.slim
p
    strong = comment.user.name
    small
        em = " created at "
        em = comment.created_at

p
    = comment.body

- if comment.user.name === current_user.name
    p
        = link_to 'Delete Comment', [comment.article, comment],
                method: :delete,
                data: { confirm: "Are you sure?" },
                class: 'btn btn-danger col-2'
hr

app/views/comments/_form.html.slim
- if flash[:error_comment]
    - flash[:error_comment].each do |msg|
        .col-sm-4.alert.alert-danger= msg

- if flash[:notice_comment]
    .col-sm-4.alert.alert-success= flash[:notice_comment]

= form_with model: [ @article, @comment ] do |form|
    div.mb-3.col-sm-6
        = form.text_area :body, class: 'form-control textarea-heigth', rows:'10'
    div
        = form.submit 'Submit', class: 'btn btn-primary'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CrudProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
        <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | CrudProject
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body
    .container
        .row
            - if current_user && current_user.role_id == 3
                ul
                    li = link_to 'Users', manage_users_path
                hr
                br
            - if user_signed_in?
                .name
                    p = current_user.name
                .col-sm-2
                    = link_to('Logout', destroy_user_session_path, method: :delete)
            - else
                .col-sm-2
                    = link_to('Login', new_user_session_path)
                .flash = flash[:error]
                .flash = flash[:notice]
            = yield

app/views/manage_users/index.html.slim
= link_to 'Back to articles', :root

h1 Utilisateurs à vérifier

- @users.each do |user|
    = form_with model: user, url: manage_user_path(user) do |f|
      .row.mb-3
        .col-sm-3
          = user.name
        .col-sm-3
          = f.collection_select(:role_id, Role.all, :id, :name, include_blank: false, label: false, class: "test")
        .col-sm-3
          = f.submit 'Valider', class:'btn btn-primary'
        .col-sm-3
          = link_to 'Supprimer', manage_user_path(user), method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-danger'